name: <test_2>

on:
  push:
    branches: ["main22"]
  pull_request:
    branches: ["main22"]

permissions:
  contents: read

jobs:
  test:
    name: Test code and model quality
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
